### ISSUE TITLE
If the output is exactly the same for all commits of 'all' or 'v6c', don't expand list of commits

### ISSUE THREAD

**Issue by MasterDuke17** [perl6/whateverable#102]
Doing so usually causes the output to be large enough that it gets gisted, which mean an extra click is needed to see the result. Instead, give the original command + the number of commits it expanded to, e.g., `¦«6c (12 commits)»: True`

This could also be done for <commit>..<commit>.

Because we don't want this to actually make the output longer, only do it if the number of commits is > 3.

**Comment by AlexDaniel** [comment]
Fixed in bbede988f697ed4b0c6598a4d471a1653678b8b2
