### ISSUE TITLE
Perl 6 rewrite

### ISSUE THREAD

**Issue by AlexDaniel** [perl6/whateverable#18]
Here is a little TODO list to track the progress:

- [x] Base class (see [Whateverable.pm6](https://github.com/perl6/bisectbot/blob/master/Whateverable.pm6))
- [x] Committable (see [Committable.p6](https://github.com/perl6/bisectbot/blob/master/Committable.p6))
- [x] Bisectable
- [x] Benchable
- [x]  Port commit https://github.com/perl6/bisectbot/commit/b19c8e2df34c2c3a0293d89b7e88e7e448e2548a to perl 6 version

Given that these are separate files, I don't think that there is a need to keep it in a separate branch. The repo may look a bit messy, but we still run Perl 5 versions, so these are still relevant.

**Comment by AlexDaniel** [comment]
Well, that's a bad sign:
```
*** Error in `/home/bisectable/.rakudobrew/moar-nom/install/bin/moar': double free or corruption (fasttop): 0x00007ff3d8650b30 ***
```

**Comment by zoffixznet** [comment]
Ouch :( I wonder if that's due to instabilities in Supplies, Channels, Promises, IO::Socket::Async, Locks... IRC::Client uses all of them and there are floppy/hanging tests in roast for those.

**Comment by AlexDaniel** [comment]
Seems to be done. We are still trying to fix a couple of bugs (and segfaults are still there), but I think that we will be able to switch to perl 6 bots soon.

**Comment by AlexDaniel** [comment]
I think that it is mostly done now. We are still using p5 bots for ``bisect:`` and ``commit:`` (you can use bot nickname to talk to p6 bots), but we will move to p6 bots completely if everything is OK for a day or two.
