### ISSUE TITLE
perl6-all-modules is no longer updated

### ISSUE THREAD

**Issue by AlexDaniel** [perl6/whateverable#184]
Just asked @moritz about [it](https://github.com/moritz/perl6-all-modules/commits/master).

Creating an issue so that it does not slip through the cracks.

**Comment by moritz** [comment]
Last update is now 2 hours ago.

**Comment by AlexDaniel** [comment]
@moritz thank you very much!

I still want to have some sort of test on my side here, so I'll reopen this with ``testneeded`` tag.

**Comment by AlexDaniel** [comment]
OK, there is a test now :)
