### ISSUE TITLE
Run multiple pieces of code in benchable

### ISSUE THREAD

**Issue by MasterDuke17** [perl6/whateverable#19]
See http://irclog.perlgeek.de/perl6-dev/2016-08-04#i_12967844

It would be nice to be able to run difference pieces of code and compare the timings (e.g., raw numbers, how much faster/slower one is over the other).

**Comment by tony-o** [comment]
There’s a module that does this if that helps at all: https://github.com/tony-o/perl6-bench



On Aug 4, 2016, at 8:14 AM, MasterDuke17 <notifications@github.com<mailto:notifications@github.com>> wrote:


See http://irclog.perlgeek.de/perl6-dev/2016-08-04#i_12967844

It would be nice to be able to run difference pieces of code and compare the timings (e.g., raw numbers, how much faster/slower one is over the other).

**Comment by MasterDuke17** [comment]
@tony-o Thanks, I used Bench to implement this in 700cb30.
