### ISSUE TITLE
We need tests

### ISSUE THREAD

**Issue by AlexDaniel** [perl6/whateverable#22]
Perhaps use whatever IRC::Client is [using](https://github.com/zoffixznet/perl6-IRC-Client/blob/master/t/release/01-basic.t).

Besides that, the only thing that we should mock or something is gist uploading.

Why? Because I am getting tired of testing everything manually.

- [x] Bisectable
- [x] Committable
- [x] Benchable
- [x] Evalable

**Comment by lembark** [comment]
> Why? Because I am getting tired of testing everything manually.


Coming into this quite late, but I could try and write some 
tests if I knew more about what you were testing.

Q: What is it that you are testing manually?

enjoi

-- 
Steven Lembark                                             3646 Flora Pl
Workhorse Computing                                   St Louis, MO 63110
lembark@wrkhors.com                                      +1 888 359 3508

**Comment by AlexDaniel** [comment]
@lembark thank you for your interest!

[README](https://github.com/perl6/whateverable/blob/master/README.md#usage-examples) has a nice list of examples. It is slightly outdated, newer versions of the bots tend to do a bit more than that (e.g. provide a link to the log), but it is still a very good list of various behaviors.

Basically, every time we do significant changes I copy-paste these examples to see if everything is alright. Usually something is broken :)

I see two ways to have tests:

1. spawn an IRC server (``Test::IRC::Server``?) and test the whole bot by sending the commands from another ``IRC::Client``
1. or just write plain unit tests. Maybe focus on [Whateverable.pm6](https://github.com/perl6/whateverable/blob/master/Whateverable.pm6) first.

I tend to prefer the former, as it easily gives high coverage with only a few tests, but feel free to do whatever you like. As long as we don't have to test stuff manually it is alright :)

Currently there are also Perl 5 bots in this repo. Forget about them, we will switch to Perl 6 bots soon.

Feel free to join ``#whateverable`` on freenode to discuss details.

**Comment by AlexDaniel** [comment]
Done! See fa3eb4e06d7a037f94333672388a924fb601ae0b and e3a9fc3a30e542412484307dd17d5098b978346b.

I did not write any tests for Benchable, hoping that @MasterDuke17 will do that (he knows Benchable better).

**Comment by MasterDuke17** [comment]
Closed with 4a05be6.
