### ISSUE TITLE
Automate nqp and moar bumps

### ISSUE THREAD

**Issue by AlexDaniel** [perl6/whateverable#232]
Last rakudo release was done with a sakefile (which unfortunately is not committed yet). I think we can extend it to create pretty version bumps like this: https://github.com/rakudo/rakudo/commit/cbce672126

Small IRC discussion: https://irclog.perlgeek.de/perl6-dev/2017-09-06#i_15124745

**Comment by zoffixznet** [comment]
Note that personally I do `make stresstest` before committing the bumps and at least a `make stresstest` needs to be done by whatever's making the bumps.

**Comment by AlexDaniel** [comment]
Yes, that's also why I think it should be done in releasable (because it already has some logic for running the stresstest).

**Comment by AlexDaniel** [comment]
No longer needed because https://github.com/zoffixznet/z/ exists now.
