### ISSUE TITLE
Proper README is needed

### ISSUE THREAD

**Issue by AlexDaniel** [perl6/whateverable#26]
Let's use wiki pages instead.

**Comment by AlexDaniel** [comment]
I moved everything from README to the wiki here: https://github.com/perl6/whateverable/wiki

The text is still a bit outdated, but things will get better shortly as we test the latest version of the bots.

**Comment by JJ** [comment]
I would vote for reopening this now. The README.md is still needed just in case one is working offline. The pointer to the wiki is kind of bare and lands you in a page with lots of links, but I can't still figure out what Whateverable actually does, other than maybe being used as a base class for bots. It would really help if a single sentence and basic usage would be included in the README.md, even if at one particular point in time it was outdated.

**Comment by AlexDaniel** [comment]
@MasterDuke17 By any chance, is it possible that you will write a few sentences in the readme to introduce the project and explain what it does? I've heard people saying “wtf is whateverable” many times, so having some basic info in the readme is perhaps actually needed.

**Comment by AlexDaniel** [comment]
@JJ what about now? I've also added https://github.com/perl6/whateverable/blob/master/CONTRIBUTING.md

**Comment by JJ** [comment]
Just in time for the Squashathon!

**Comment by AlexDaniel** [comment]
I'll call that good enough. Please let me know if something else should be included in it.
