### ISSUE TITLE
New bot: Notable

### ISSUE THREAD

**Issue by AlexDaniel** [perl6/whateverable#285]
WIP

**Comment by AlexDaniel** [comment]
I've been banging my head against multidispatch bugs for the last hour. Blocked for now: https://github.com/rakudo/rakudo/issues/1481

**Comment by zoffixznet** [comment]
> Blocked for now

You can just use blocks instead thunks:

```perl-6
   multi sub foo($x where {?/{dd $x}./}) {};
```

**Comment by AlexDaniel** [comment]
@zoffixznet thanks, that does help a little bit, but there's still something fishy with multidispatch. I'll have to look into it to see what's is going wrong exactly, but here's a teaser:

> \<AlexDaniel\> weekly: foo
> \<notable6test\> AlexDaniel, Noted!
> \<AlexDaniel\> notable6test: weekly foo
> \<notable6test\> AlexDaniel, Noted!
> \<AlexDaniel\> notable6test: weekly foo
> \<notable6test\> AlexDaniel, Noted!
> \<AlexDaniel\> weekly: foo
> \<notable6test\> AlexDaniel, I cannot recognize this command. See wiki for some examples: https://github.com/perl6/whateverable/wiki/Notable

**Comment by AlexDaniel** [comment]
Ah, actually. I think I had another candidate which needed the workaround that you mentioned. Seems to be OK now.
