### ISSUE TITLE
Installation fails in 2018.04

### ISSUE THREAD

**Issue by JJ** [perl6/whateverable#322]
It's [Stats](https://github.com/MattOates/Stats) what is actually failing.
```
===> Testing: Stats:ver<0.0.5>:auth<github:MattOates>
# Failed test 'Correlation coefficient is 1 for same values'
# at t/correlation.t line 12
# expected: '1'
#      got: '0.9999999999999998'
# Failed test 'Correlation correctly calculated'
# at t/correlation.t line 13
# expected: '-1'
#      got: '-0.9999999999999998'
# Looks like you failed 2 tests of 6
```

**Comment by AlexDaniel** [comment]
@JJ++ for the pull request: https://github.com/MattOates/Stats/pull/9

**Comment by AlexDaniel** [comment]
@JJ by the way, maybe we should do https://github.com/perl6/whateverable/issues/288? Lets maybe at least check that modules are installable?

**Comment by AlexDaniel** [comment]
Given that the PR is now merged, I think this is fixed.
