### ISSUE TITLE
Tellable should format CTCP ACTION

### ISSUE THREAD

**Issue by taboege** [perl6/whateverable#360]
Currently it prints the raw message "\x[01]ACTION …\x[01]", as seen [here](https://colabti.org/irclogger/irclogger_log/perl6?date=2019-09-18#l2):
```
<TimToady> ␁ACTION had the power company swapping his electric meter, and it broke  my / key␁
```
when something like this would be more common instead
```
* TimToady had the power company swapping his electric meter, and it broke  my / key
```

**Comment by AlexDaniel** [comment]
So! `/me` action from the discrod bridge seems to look like this:

https://colabti.org/irclogger/irclogger_log/perl6?date=2019-09-18#l524

![image](https://user-images.githubusercontent.com/5507503/65191235-ff442780-da7b-11e9-947a-19eb7f88d85f.png)
